### ISSUE TITLE
我记得你以前是用python在写啊,怎么改成.net了

### ISSUE THREAD

**Issue by ghost** [Speiser/ClassicEmu#1]

**Comment by Speiser** [comment]
Hi, I´m not speaking Chinese.  
What I got from Google Translate: If you are looking for the old python code, there is a "old_python" branch you can check out.  
Hope that helps

**Comment by ghost** [comment]
> Hi, I´m not speaking Chinese.
> What I got from Google Translate: If you are looking for the old python code, there is a "old_python" branch you can check out.
> Hope that helps


Hǎo de, wǒ qù zhǎo yīxià kàn kàn, xièxiè
13/5000
Ok, let me go and have a look, thank you.

**Comment by ghost** [comment]
> Hi, I´m not speaking Chinese.
> What I got from Google Translate: If you are looking for the old python code, there is a "old_python" branch you can check out.
> Hope that helps

Hey, brother! I want to write this server in php. Can you give me a server API interface document?

**Comment by Speiser** [comment]
There is no document, just trying to figure out how it works myself. As a reference you can check TrinityCore or Mangos

**Comment by ghost** [comment]
> There is no document, just trying to figure out how it works myself. As a reference you can check TrinityCore or Mangos

Okay thank you
